name: Testing
on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
    tags-ignore: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
    container:
      image: python:${{ matrix.python }}-alpine
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
          - 4510-4559:4510-4559
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install testing dependencies
        run: pip3 install -e '.[dev]'

      - name: Run flake8 tests
        run: flake8 --output build/flake8.txt --tee

      - name: Run tests
        run: coverage run && coverage report && coverage xml
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: local
          AWS_SECRET_ACCESS_KEY: development
          ENDPOINT_URL: http://localstack:4566
      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.2
        if: github.event_name == 'push' && github.repository == 'gmr/ssm-ps-template'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: build/coverage.xml
          flags: unittests
